### ISSUE TITLE
Frech

### ISSUE THREAD

**Issue by SirFrancisBillard** [BillardDRP/FrechConjugationThing#3]
YOU SPELLED IT WRONG GOD DAMN IT THAT WILL HAUNT EVERYBODY FOREVER

I know I can change name but I want you to do it so I don't screw it up

**Comment by irefl** [comment]
what?

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by irefl** [comment]
the repo name?

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by SirFrancisBillard** [comment]
Yes, but we MIGHT be able to change it. I think? Maybe?

**Comment by SirFrancisBillard** [comment]
Well, I know we CAN change it, just if we should because of the stuff it might do

**Comment by SirFrancisBillard** [comment]
Especially because of it being a github pages site and all

**Comment by irefl** [comment]
huh

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by irefl** [comment]
there is no gh-pages yet

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by irefl** [comment]
ah shit, ill fix it, but ill back it all up first :P
